### ISSUE TITLE
Recv all / send all

### ISSUE THREAD

**Issue by MatthewScholefield** [Ybalrid/kissnet#19]
I'd imagine the majority of users would end up writing their own `recvAll` and `sendAll` wrappers around tcp sockets. Would it make sense to include this in the socket library?

Edit: Also, unless I'm missing something, shouldn't the examples in the README also wrap each `recv`/`send` in a while loop? (even though with such small buffer size there wouldn't typically be a partial read/write)

**Comment by andersc** [comment]
I wrote a wrapper for that, it might not be what you look for but just want to mention that anyway. `https://github.com/Unit-X/efp`
There is a kissnet example here ->
https://github.com/Unit-X/ts2efp

The idea with that framing is that a receiver will send some data and then from multiple packets be able to assemble the data again.  If the data is broken you will also get that indication and you can also associate data with an identifier. The license is MIT so it's free to use in any commercial project. Some people started using it specially for media but there are also other using it for transporting just arbitrary data.

BTW... TNX @Ybalrid for making this portable network stack so that we at all cost can avoid boost ;-)

**Comment by Ybalrid** [comment]
Examples are unrealistic and contrived *just to show* what's the library is about.

I do think adding a `recv_all`/`send_all` is out of scope for this library. I just want to wrap the abstraction of "a file that you read/write bytes into and it goes to/from the network" that are socket in a more `C++` way than using the BSD sockets API (and the windows ripoff that is WinSock) are. As they are fundamentally old clunky C APIs. 

@andersc This elastic frame thing is interesting. I'm gonna bookmark that and dig about it later. However, again, this kind of thing is way out-of-scope and high-level for kissnet.

Feel free to build anything you want on top of it in your own projects, that's the goal! 😄

**Comment by Ybalrid** [comment]
So with the rationale above, I'm gonna close this discussion.
