### ISSUE TITLE
tcp_socket is non-copyable, making it hard to wrap in a class

### ISSUE THREAD

**Issue by skelleher** [Ybalrid/kissnet#54]
tcp_socket is non-copyable.  This means that the following code is impossible:

auto clientSocket = serverSocket.accept();
m_socket = clientSocket;

Also can't add a client socket to a lookup table, or a message queue, for sending responses to the correct client:

responseQueue.socket = clientSocket;
  or
map[clientID] = clientSocket;

Is this a strongly-held decision, or would you be open to a PR allowing copy/assignment?
I've tried m_socket = std::move(clientSocket) but it invokes the destructor, closing the socket. Still debugging that....

**Comment by Ybalrid** [comment]
The socket class is not copyable by design. It holds the lifetime to the *actual socket* file descriptor underneath.

However, it should be movable, that is interesting you came up with a problem doing so...

(If your code needs to *reference* a socket outside to where it is *owned*, you probably should use a pointer, or a reference, but not the value-type ?)

**Comment by skelleher** [comment]
That makes sense.  However the move assignment operator does call closesocket():

```
       socket& operator=(socket&& other) noexcept
        {
            if (this != &other)
            {
                if (!(sock < 0) || sock != INVALID_SOCKET)
                {
                    closesocket(sock);
                }
         }
```         
So I'm not sure how the socket would be usable after a move.

Also the socket returned by serverSocket.accept() is a temp object created on the stack.  So I can't take a pointer to it, or pass it to a worker thread; after std::move the destructor is probably called because the original goes out of scope when the main function returns.

In my case I want a clientSocket to be passed off to another thread or library instead of my main() loop doing all the socket IO.

**Comment by Ybalrid** [comment]
Ah, I think I grasp your issue. 

No, moving does not close *your* socket, but it might close *an old* socket that was stored in that object.

For the clarity of the discussion, here's the full code of the operator= overload in question:

```cpp
		socket& operator=(socket&& other) noexcept
		{
			if (this != &other)
			{
				if (!(sock < 0) || sock != INVALID_SOCKET)
					closesocket(sock);

				KISSNET_OS_SPECIFIC_PAYLOAD_NAME = std::move(other.KISSNET_OS_SPECIFIC_PAYLOAD_NAME);
				bind_loc						 = std::move(other.bind_loc);
				sock							 = std::move(other.sock);
				socket_input					 = std::move(other.socket_input);
				socket_input_socklen			 = std::move(other.socket_input_socklen);
				getaddrinfo_results				 = std::move(other.getaddrinfo_results);
				socket_addrinfo					 = std::move(other.socket_addrinfo);

#ifdef KISSNET_USE_OPENSSL
				pSSL		   = other.pSSL;
				pContext	   = other.pContext;
				other.pSSL	   = nullptr;
				other.pContext = nullptr;
#endif

				other.sock				  = INVALID_SOCKET;
				other.getaddrinfo_results = nullptr;
				other.socket_addrinfo	  = nullptr;
			}
			return *this;
		}
```


There are _two_ socket objects dancing here : `*this` and `other`. we are __moving from__ `other` into `this`. `other` here is your new client socket. `this` is an empty socket object that was created in your map or list or wherever you decided to store this> 🙂 

Here's what this function **actually does**:

 - If I `this` the same socket as `other`, do nothing
 - If `this` **was** a valid socket, close it
 - copy/move all relevant members of `other` into `this`
 - set all `other` members so this is now a invalid "empty shell" moved-from object
 - return reference to `this`
 
 
 So, the call to `closesocket()` here is *potentially closing* the existing socket in the object were you are moving your socket **into**, then it is "neutering" the content of the old socket object so it does not hold a valid socket anymore.
 
 If you are familiar with move-semantics in "modern" C++, that should be a familiar pattern.
 
 As a practical example: If you move your socket into your look-up table like you suggest, 
 
 ```cpp
  auto clientSocket = serverSocket.accept(); 
  map[clientID] = std::move(clientSocket); // <-- we gonna dissect what is going on in this line
  ```
 
 Assuming `clientID` was not in the map just yet, the following occur in the line I have highlighted in a comment:
 
 - `map<socket>::operator[]()` gets called
   - it creates a empty socket object, the default constructor of the socket class gets called
   - it retuns a non-const reference to this object
 - `std::move()` cast the clientSocket from a tcp_socket to a tcp_socket&& (r-value reference)
 - `operator=(socket&&)` get's called with clientSocket's reference
   - the socket object stored in the map contains a invalid (not initialized) socket file descriptor, so closeSocket is not called
   - all the underlying data get's moved
   - `clientSocket` now is not your socket anymore
   - `map[clientID]` now **has taken ownership** of the socket.

When the function that does this end, clientSocket goes out of scope. It's destructor gets called, but since it does not hold the socket, nothing happens. Your socket is open and connected up until an error occurs (disconnected somehow) or you discard it by:

- overwriting it in the map
- erasing it from the map
- discarding the map altogether

Does this clarify the operation ? You could try to step through the operator with a debugger and confirm that it is not closing your newly accepted client socket.

**Comment by skelleher** [comment]
I can't believe I missed that it was closing this->socket. *face palm* I should have stepped through the code instead of just reading it quickly.

That is probably the most complete and helpful response I have received to a question in a long time. Thank you for taking the time to explain it in such detail.

**Comment by skelleher** [comment]
I'm (obviously) able to move the socket to my lookup table now and that seems to be OK, so I will close this issue.
